apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: adhp/zdv-frontend
  newName: adhp/zdv-frontend
  newTag: dev-04ac404
- name: denartcc/api
  newName: adhp/api
  newTag: dev-8f35fc4
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
