apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: adhp/zdv-frontend
  newName: adhp/frontend
  newTag: zdv-main-8e41de9
- name: denartcc/api
  newName: adhp/api
  newTag: dev-c05f37b
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
