apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
images:
- name: denartcc/api
  newName: adhp/api
  newTag: 3d1aae5
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
