apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-denartcc-org-tls
spec:
  dnsNames:
  - www.zdvartcc.org
  - zdvartcc.org
  - new.zdvartcc.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: www-denartcc-org-tls
