apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
- auth/certificate.yaml
- auth/deployment.yaml
- auth/ingress.yaml
- auth/service.yaml
- discord/certificate.yaml
- discord/deployment.yaml
- discord/ingress.yaml
- discord/service.yaml
- mysql-backup/cronjob.yaml
- bot/deployment.yaml
- roster-sync/cronjob.yaml
images:
- name: adhp/zdv-frontend
  newName: adhp/frontend
  newTag: zdv-v1.1.1-4860898
- name: denartcc/api
  newName: adhp/api
  newTag: main-921986f
- name: denartcc/bot
  newName: adhp/bot
  newTag: main-1ec0518
- name: vzanartcc/auth
  newName: adhp/auth
  newTag: 72032a6
