apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
- auth/certificate.yaml
- auth/deployment.yaml
- auth/ingress.yaml
- auth/service.yaml
- mysql-backup/cronjob.yaml
- bot/deployment.yaml
images:
- name: denartcc/api
  newName: adhp/api
  newTag: main-646a649
- name: vzanartcc/auth
  newName: adhp/auth
  newTag: 72032a6
