apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
- auth/certificate.yaml
- auth/deployment.yaml
- auth/ingress.yaml
- auth/service.yaml
- mysql-backup/cronjob.yaml
- bot/deployment.yaml
- roster-sync/cronjob.yaml
images:
- name: adhp/zdv-frontend
  newName: adhp/frontend
  newTag: zdv-main-7860247
- name: denartcc/api
  newName: adhp/api
  newTag: main-93ac607
- name: vzanartcc/auth
  newName: adhp/auth
  newTag: 72032a6
