apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-denartcc-org-tls
spec:
  dnsNames:
  - auth.denartcc.org
  - auth.zdvartcc.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-auth-denartcc-org
